#!/usr/bin/env bash

is_dir() { [[ -d "$1" ]]; }
is_set() { [[ -n "$1" ]]; }
is_empty_array() { [[ 0 == "${#@}" ]]; }

write() {
    if is_set "$NULL_TERMINATED"; then
        printf '%s\0' "$1"
    else
        printf '%s\n' "$1"
    fi
}


#depth_first() {
#    for d in "$@"; do
#        #shopt -s globstar
#        for f in "${d%/}/"**; do
#            if is_dir "$f"; then
#                write "$f"
#                depth_first "$f"
#            else
#                write "$f"
#            fi
#        done
#    done
#}

breadth_first() {
    local depth="$1"; shift
    local stack=( "$@" )
    local stack2=()
    while ((depth-- >= 0 && ${#stack[@]} > 0 )); do
        for d in "${stack[@]}"; do
            for f in "${d%/}"/*; do
                if is_dir "$f"; then
                    write "$f"
                    stack2+=("$f")
                else
                    write "$f"
                fi
            done
        done
        stack=( "${stack2[@]}" )
        stack2=()
    done
}

print_help() {
    echo "DESCRIPTION"
    echo "  Walks dirs recursively breadth first."
    echo "  More than one dir can be walked e.g. walk /path/to/dir1/ /path/to/dir2/"
    echo "  If no dir is provided then walks the current dir."
    echo "OPTIONS"
    echo -e "  -d\tLimit depth of search."
    echo -e "  -0\tOutput null terminated string."
    echo -e "  -h\tShow Usage."
}

main() {
    local depth=1000000

    local opt
    while getopts "h0d:" opt; do
        case "$opt" in
            h)
                print_help
                exit 0
                ;;
            0)
                NULL_TERMINATED=1
                ;;
            d)
                depth="$OPTARG"
                ;;
            *)
                print_help
                exit 1
                ;;
        esac
    done
    shift $((OPTIND - 1))

    if is_empty_array "$@"; then
        breadth_first $depth "."
    else
        breadth_first $depth "$@"
    fi
}; main "$@"
